language: go

stages:
  - lint
  - test

go:
  - 1.12.x
  - 1.13.x
  - tip

env: GO111MODULE=on

before_install: go get -u github.com/kyoh86/richgo

script:
  - richgo test -v ./...
  - go build

matrix:
  allow_failures:
    - go: tip
  include:
    - stage: lint
      go: 1.13.x
      before_install: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.19.1
      script: golangci-lint run -v
