language: go

stages:
  - diff
  - test

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

env:
  - GO111MODULE=on

matrix:
  allow_failures:
    - go: tip
  include:
    - stage: diff
      go: 1.13.x
      script: diff -u <(echo -n) <(gofmt -d -s .)

before_install: go get -u github.com/kyoh86/richgo

script:
  - richgo test -v ./...
  - go build
  - if [ -z $NOVET ]; then
      diff -u <(echo -n) <(go vet . 2>&1 | grep -vE 'ExampleCommand|bash_completions.*Fprint');
    fi
